apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bash
  template:
    metadata:
      labels:
        app: bash
    spec:
      containers:
      - name: bash
        image: ellerbrock/alpine-bash-curl-ssl
        command: ["/bin/sh"]
        args: ["-c", "sleep 1000000"]
        tty: true
