apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app: lunchandlearn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lunchandlearn
  template:
    metadata:
      labels:
        app: lunchandlearn
    spec:
      containers:
      - name: foo-app
        image: hashicorp/http-echo:0.2.3
        args:
        - "-text=foo"
