apiVersion: v1
kind: Service
metadata:
  name: simple-go-server-service-cluster-ip
  labels:
    app: lunchandlearn
spec:
  selector:
    app: lunchandlearn
  ports:
    - protocol: TCP
      port: 5678
