apiVersion: v1
kind: Service
metadata:
  name: simple-go-server-service-node-port
  labels:
    app: lunchandlearn
spec:
  type: NodePort
  selector:
    app: lunchandlearn
  ports:
    - protocol: TCP
      port: 5678
