apiVersion: v1
kind: Service
metadata:
  name: simple-go-server-service-load-balancer
  labels:
    app: lunchandlearn
spec:
  type: LoadBalancer
  selector:
    app: lunchandlearn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
